### ISSUE TITLE
Custom Meta Visible in Receipt Generated by Woocommerce POS

### ISSUE THREAD

**Issue by WarenGonzaga** [alexmigf/stock-locations-for-woocommerce#30]
Hi @alexmigf, your fix is great! However there is issue when generating a receipt the meta from stock allocation is mysteriously included. Is there a way to make this hidden?

![image](https://user-images.githubusercontent.com/15052701/94758531-f34dae00-03cf-11eb-9764-f16ea9bb7a5e.png)

**Comment by WarenGonzaga** [comment]
@alexmigf don't worry I found a solution myself... just add this simple but advanced css selection on custom css via receipt customization.

```css
/* Remove Custom Meta after SKU */
.receipt-product-sku + small,
.receipt-product-sku + small + small {
	display: none !important;
}
```

I hope you can add a simple way to automagically remove that meta data being included in printing receipt with Woocommerce POS
